version: '3.9'

services:
  postgres:
    image: postgres
    container_name: node-server
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nodeapp
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
    driver: local
